# Header
menu:
  Home: /
  About: /about.html
# Archives: /archives
# rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud

# Miscellaneous
google_analytics: UA-46195295-1
favicon: /img/favicon.png
twitter: nakajmg
google_plus:
fb_admins:
fb_app_id:
